# Generated by Django 5.0.6 on 2024-07-10 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0002_alter_building_options_alter_address_street'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.PositiveBigIntegerField(verbose_name='Доля %')),
                ('is_floor_chief', models.BooleanField(default=False, verbose_name='Главный по этажу')),
                ('is_entrance_chief', models.BooleanField(default=False, verbose_name='Главный по подъезду')),
                ('is_building_chief', models.BooleanField(default=False, verbose_name='Главный по дому')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='structure.apartment', verbose_name='Адрес')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жилец',
                'verbose_name_plural': 'Жильцы',
                'ordering': ('apartment',),
            },
        ),
    ]
