# Generated by Django 5.0.6 on 2024-07-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='is_building_chief',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_entrance_chief',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_floor_chief',
        ),
        migrations.AddField(
            model_name='participant',
            name='other_contacts',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Другие контакты'),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='participant',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram'),
        ),
    ]
