# Generated by Django 5.0.6 on 2024-07-11 07:41

import django.db.models.deletion
import voting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '0002_remove_participant_is_building_chief_and_more'),
        ('structure', '0002_alter_building_options_alter_address_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingChief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Начало срока')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Завершение срока')),
                ('active', models.BooleanField(default=False, verbose_name='Действующий')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.address', verbose_name='Адрес')),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participant.participant', verbose_name='Ответственный за дом')),
            ],
            options={
                'verbose_name': 'Ответсвенный за дом',
                'verbose_name_plural': 'Ответсвенные по домам',
                'ordering': ('-active', 'address', '-start_date'),
            },
        ),
        migrations.CreateModel(
            name='EntranceChief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Начало срока')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Завершение срока')),
                ('entrance_number', models.PositiveSmallIntegerField(verbose_name='Номер подъезда')),
                ('active', models.BooleanField(default=False, verbose_name='Действующий')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.address', verbose_name='Адрес')),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participant.participant', verbose_name='Ответственный за подъезд')),
            ],
            options={
                'verbose_name': 'Ответсвенный за подъезд',
                'verbose_name_plural': 'Ответсвенные по подъездам',
                'ordering': ('-active', 'address', 'entrance_number', '-start_date'),
            },
        ),
        migrations.CreateModel(
            name='FloorChief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Начало срока')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Завершение срока')),
                ('entrance_number', models.PositiveSmallIntegerField(verbose_name='Номер подъезда')),
                ('floor_number', models.PositiveSmallIntegerField(verbose_name='Номер этажа')),
                ('active', models.BooleanField(default=False, verbose_name='Действующий')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.address', verbose_name='Адрес')),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participant.participant', verbose_name='Ответсвенный за этаж')),
            ],
            options={
                'verbose_name': 'Ответсвенный за этаж',
                'verbose_name_plural': 'Ответсвенные по этажам',
                'ordering': ('-active', 'address', 'entrance_number', 'floor_number', '-start_date'),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('FLOOR', 'Ответсвенный за этаж'), ('ENTRANCE', 'Ответственный за подъезд'), ('BUILDING', 'Ответсвенный за дом')], max_length=20, verbose_name='Предмет голосования')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Начало голосования')),
                ('vote_end', models.DateTimeField(default=voting.models.vote_end, verbose_name='Завершение голосования')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participant.participant', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'Голосования',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='VoteResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField(verbose_name='Выбор')),
                ('choice_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выбора')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participant.participant', verbose_name='Голос')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voting.vote', verbose_name='Голосование')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
                'ordering': ('-choice_date', '-vote'),
            },
        ),
    ]
