# Generated by Django 5.0.6 on 2024-07-10 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации заявки')),
                ('text', models.TextField(verbose_name='Заявка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participant.participant', verbose_name='Автор заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-register_date',),
            },
        ),
    ]
