# Generated by Django 5.0.6 on 2024-07-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ('address',), 'verbose_name': 'Здание', 'verbose_name_plural': 'Здания'},
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='street_addresses', to='structure.street', verbose_name='Улица'),
        ),
    ]
